### ISSUE TITLE
readme example for local browsers hanging

### ISSUE THREAD

**Issue by davidtheclark** [ekryski/launchpad#38]
If I run the following script:

```js
var launchpad = require('launchpad');

launchpad.local(function(err, local) {
	console.log('launchpad.local callback');
	if (err) { throw err; }
	local.browsers(function(err2, browsers) {
		console.log('local.browsers callback');
		if (err2) { throw err2; }
		console.log(browsers);
	});
});
```

... my console output is `launchpad.local callback` and then nothing happens.

I *think* this is following the example in the readme properly. Am I missing something, or is this a bug?

**Comment by daffl** [comment]
Sorry I somehow missed this issue. You can set the `DEBUG=launchpad:*` environment variable to get more information on what it is trying to do while discovering the browsers.

I'm closing the issue since it has been around for a while. Please reopen if you have more information.
