### ISSUE TITLE
0.5.2 throws errors if M$ Edge not installed

### ISSUE THREAD

**Issue by jasongardnerlv** [ekryski/launchpad#65]
I have a build that just pulled the latest 0.5.2 tag today.  This is on a Windows Server 2008 VM (Edge is not installed, Chrome is the only browser being launched currently).  The build throws:

 `Error: ENOENT: no such file or directory, scandir 'C:\Windows\SystemApps'`

I created the **SystemApps** folder and re-ran, and got this:

`TypeError: Path must be a string. Received undefined`

added one more folder 'C:\Windows\SystemApps\Microsoft.MicrosoftEdge123' and build now succeeds.

**Comment by matthewp** [comment]
I'm seeing this as well, reading a directory that doesn't exist throws, so this code needs to account for that. Will submit a PR shortly.
